import { createAdminClient } from '@/lib/supabase/server';
import {
  buildCaseStudyLongHtml,
  type LongFormArtifacts,
} from '@/components/pdf/caseStudyLongHtml';
import { buildCaseStudyShortHtml } from '@/components/pdf/caseStudyShortHtml';
import { synthesizeShortFormContent } from '@/lib/ai/synthesizeShortForm';
import { renderHtmlToPdf } from '@/lib/pdf/renderHtmlToPdf';
import type { CaseStudy } from '@/lib/types';

/** Which PDF to render: the short-form 3-pager or the long-form story. */
export type PdfVariant = 'short' | 'long';

export interface CaseStudyPDFProps {
  caseStudy: CaseStudy;
  clientName: string;
  serviceProvided?: string;
}

/**
 * Props for PDF generation. Both variants use the base case study; the
 * long-form additionally consumes Phase 3/5 artifacts for adaptive depth.
 * Artifacts are optional so re-render flows degrade gracefully when absent.
 */
export type GeneratePdfProps = CaseStudyPDFProps & LongFormArtifacts;

export async function generatePDF(
  props: GeneratePdfProps,
  variant: PdfVariant = 'short'
): Promise<Buffer> {
  if (variant === 'long') {
    return renderHtmlToPdf(buildCaseStudyLongHtml(props), {
      runningHeader: { left: 'CaseForge', right: `${props.clientName} · Case Study` },
      runningFooter: { left: 'Generated by CaseForge' },
    });
  }

  // Short-form: AI-assisted placeholder fill → HTML template → Puppeteer PDF.
  // The template includes its own per-page header/footer bars, so no running
  // header/footer is passed to renderHtmlToPdf (that would duplicate them).
  const content = await synthesizeShortFormContent({
    caseStudy: props.caseStudy,
    clientName: props.clientName,
    serviceProvided: props.serviceProvided,
  });
  return renderHtmlToPdf(buildCaseStudyShortHtml(content), {
    runningHeader: { left: 'CaseForge', right: `${props.clientName} · Case Study` },
    runningFooter: { left: 'Generated by CaseForge' },
  });
}

/** Render one variant and upload it to Supabase Storage. Returns the public URL. */
export async function generateAndUploadPDF(
  campaignId: string,
  props: GeneratePdfProps,
  variant: PdfVariant = 'short'
): Promise<string> {
  const buffer = await generatePDF(props, variant);
  const supabase = createAdminClient();
  const path = `${campaignId}-${variant}.pdf`;

  const { error } = await supabase.storage
    .from('pdfs')
    .upload(path, buffer, {
      contentType: 'application/pdf',
      upsert: true,
    });

  if (error) throw new Error(`PDF storage upload failed: ${error.message}`);

  const {
    data: { publicUrl },
  } = supabase.storage.from('pdfs').getPublicUrl(path);

  // The storage path is fixed (upsert), so the public URL is stable. Append a
  // version param so re-rendered PDFs aren't served stale from browser/CDN cache.
  return `${publicUrl}?v=${Date.now()}`;
}

/** Render and upload both the short-form and long-form PDFs. */
export async function generateAndUploadBothPDFs(
  campaignId: string,
  props: GeneratePdfProps
): Promise<{ pdfUrl: string; pdfUrlLong: string }> {
  const [pdfUrl, pdfUrlLong] = await Promise.all([
    generateAndUploadPDF(campaignId, props, 'short'),
    generateAndUploadPDF(campaignId, props, 'long'),
  ]);
  return { pdfUrl, pdfUrlLong };
}
